name: CI - Deploy to GitHub Pages

on:
  push:
    branches:
      - pr-gh-pages-ci

# note: this could be done better in any number of ways
jobs:
  build:
    runs-on: [ubuntu-22.04]
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      
      - name: Update file layout
        run: |
          mkdir public
          cp -r core public
          cp -r web-ui/* public
          sed -i -e 's/\.\.\/core\//\.\/core\//g' ./public/main.js
          sed -i -e 's/\.\.\/core\//\.\/core\//g' ./public/completion.js
    
      - name: Commit back to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public && git commit -m "GitHub Pages Deployment"
          git subtree push --force --prefix public origin gh-pages