name: CI - Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# note: this could be done better in any number of ways
jobs:
  build:
    runs-on: [ubuntu-22.04]
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      
      - name: Update file layout
        run: |
          mkdir docs
          echo 'xw.macyler.moe' > ./docs/CNAME
          cp -r core docs
          cp -r web-ui/* docs
          sed -i -e 's/\.\.\/core\//\.\/core\//g' ./docs/main.js
          sed -i -e 's/\.\.\/core\//\.\/core\//g' ./docs/completion.js
    
      - name: Commit back to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update GitHub Pages"
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: gh-pages
          skip_fetch: true
          skip_checkout: true
          push_options: '--force'
